### ISSUE TITLE
gem does not install 0.0.8

### ISSUE THREAD

**Issue by martinr103** [wshihadeh/fluent-plugin-filter-kv-parser#7]
Hello there,

I am trying to install the latest version 0.0.8 - and in fact I need it because of the new 'keys_prefix' config parameter - but whatever I do, I always keep getting version 0.0.7 installed.

My target system is Ubuntu 18.04
I tried with the original fluentd, and also with the Treasure Data (td-agent4) version.
Both gem installations only install 0.0.7 and not 0.0.8.

Why is that ?

**Comment by wshihadeh** [comment]
can you try to use `v0.0.9` ?

**Comment by martinr103** [comment]
Now it does install 0.0.9
Great!
Thanks for your quick assistance.
